# Define the services for your application
services:
  # Web service for your Node.js backend
  - type: web
    name: adunke-server
    env: node
    region: oregon
    plan: free
    branch: indev
    repo: https://github.com/Martins-O/adunke-server
    buildCommand: npm install
    startCommand: npm start
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        sync: false
      - key: VITE_API_URL
        value: "https://adunke-server.onrender.com"
      - key: CLOUDINARY_CLOUD_NAME
        value: "dlbyxoyyg"
      - key: CLOUDINARY_API_KEY
        value: "616498913116735"
      - key: CLOUDINARY_API_SECRET
        value: "W-8YI9ZJI90Eqb3h_nW2qgux1q0"
      - key: DATABASE_URL
        sync: false